# For details on buf.yaml configuration, visit https://buf.build/docs/configuration/v2/buf-yaml
version: v2
### got extra deps
deps:
  - buf.build/grpc-ecosystem/grpc-gateway
  - buf.build/googleapis/googleapis
modules:
  - path: source/0_generate/proto
lint:
  use:
    - STANDARD
breaking:
  use:
    - FILE