version: v2
clean: true
managed:
  enabled: true
  disable:
    # Don't modify any file option or field option for googleapis
    - module: buf.build/googleapis/googleapis
    # Don't modify any file option or field option for grpc-gateway
    #- module: buf.build/grpc-ecosystem/grpc-gateway
  override:
    - file_option: go_package_prefix
      ### any generate package got this prefix
      value: buf-p1/internal/controller/grpc/proto
plugins:
  ### classic bin for proto struct generate
  - local: protoc-gen-go
    out: internal/controller/grpc/proto
    opt: paths=source_relative
  ### classic bin for proto service generate
  - local: protoc-gen-go-grpc
    out: internal/controller/grpc/proto
    opt: paths=source_relative
inputs:
  - directory: source/0_generate