# For details on buf.yaml configuration, visit https://buf.build/docs/configuration/v2/buf-yaml
version: v2
### got extra deps
deps:
  - buf.build/grpc-ecosystem/grpc-gateway
  - buf.build/googleapis/googleapis
modules:
  # Очень важно, что путь указан до папки, которая содержит все proto
  - path: source/2_breaking_change/proto
# Настройки проверки обратной совместимости
breaking:
  use:  # Какие правила проверки использовать
    - FILE  # Проверять изменения на уровне файлов (рекомендуемый базовый уровень)
  # ИЛИ можно явно указать конкретные правила:
  # against_input:  # Альтернативный подход - сравнение с исходным состоянием
  #   source:
  #     branch: main  # Сравнивать с веткой main
  #   exclude:  # Исключить из проверки
  #     - acme/weather/v1/weatcher.proto  # Если есть временные исключения
  # Игнорировать изменения в deprecated полях
  ignore_unstable_packages: true # кажется, что это не работает